const User = require("../models/User");
const PDFDocument = require("pdfkit");

// GET /coordinator/certificates/pdf?month=May 2026
const downloadCertificatesPDF = async (req, res) => {
  try {
    const { month } = req.query;

    const students = await User.find({
      role:       "student",
      department: req.user.department,
      isActive:   true,
    }).select("name rollNo branch section certifications");

    const doc = new PDFDocument({ margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=certificates-${month || "all"}.pdf`
    );
    doc.pipe(res);

    // ── Header ──
    doc
      .fontSize(18)
      .fillColor("#14532d")
      .text("Sreenidhi Institute of Science & Technology", { align: "center" })
      .moveDown(0.3)
      .fontSize(13)
      .fillColor("#333")
      .text(
        `Student Certifications Report — ${month || "All Time"}`,
        { align: "center" }
      )
      .moveDown(0.3)
      .fontSize(11)
      .fillColor("#666")
      .text(`Department: ${req.user.department}`, { align: "center" })
      .text(`Generated: ${new Date().toDateString()}`,  { align: "center" })
      .moveDown(0.5);

    doc
      .moveTo(50, doc.y)
      .lineTo(560, doc.y)
      .strokeColor("#14532d")
      .stroke()
      .moveDown(0.5);

    let totalCerts = 0;

    students.forEach((student) => {
      const certs = month
        ? student.certifications.filter((c) => c.uploadedMonth === month)
        : student.certifications;

      if (!certs.length) return;

      totalCerts += certs.length;

      // Student name
      doc
        .fontSize(12)
        .fillColor("#14532d")
        .text(`${student.name} (${student.rollNo || "N/A"})`)
        .fontSize(10)
        .fillColor("#666")
        .text(`Branch: ${student.branch || "N/A"} | Section: ${student.section || "N/A"}`)
        .moveDown(0.3);

      // Certificates
      certs.forEach((cert, i) => {
        doc
          .fontSize(11)
          .fillColor("#333")
          .text(`  ${i + 1}. ${cert.title}`)
          .fontSize(10)
          .fillColor("#666")
          .text(`     Issued by : ${cert.issuedBy    || "N/A"}`)
          .text(`     Date      : ${cert.issuedDate  ? new Date(cert.issuedDate).toDateString() : "N/A"}`)
          .text(`     Month     : ${cert.uploadedMonth || "N/A"}`)
          .text(`     Details   : ${cert.description  || "N/A"}`)
          .moveDown(0.3);
      });

      doc
        .moveTo(50, doc.y)
        .lineTo(560, doc.y)
        .strokeColor("#e5e7eb")
        .stroke()
        .moveDown(0.4);
    });

    // ── Footer ──
    doc
      .moveDown(0.5)
      .fontSize(11)
      .fillColor("#333")
      .text(`Total Certifications: ${totalCerts}`, { align: "right" })
      .moveDown(0.5)
      .fontSize(10)
      .fillColor("#888")
      .text("Auto-generated by Mentoring Hub", { align: "center" });

    doc.end();
  } catch (err) {
    console.error(err.message);
    res.status(500).json({ msg: "Server error" });
  }
};

module.exports = { downloadCertificatesPDF };