const PDFDocument = require("pdfkit");

const generateWeeklyReportPDF = (report, mentor, res) => {
  const doc = new PDFDocument({ margin: 50 });

  // Stream directly to response
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename=weekly-report-${report.weekStartDate
      .toISOString()
      .split("T")[0]}.pdf`
  );
  doc.pipe(res);

  // ── Header ──
  doc
    .fontSize(20)
    .fillColor("#14532d")
    .text("Sreenidhi Institute of Science & Technology", { align: "center" })
    .moveDown(0.3)
    .fontSize(14)
    .fillColor("#333")
    .text("Weekly Mentoring Report", { align: "center" })
    .moveDown(0.5);

  // ── Divider ──
  doc
    .moveTo(50, doc.y)
    .lineTo(560, doc.y)
    .strokeColor("#14532d")
    .stroke()
    .moveDown(0.5);

  // ── Mentor Info ──
  doc
    .fontSize(11)
    .fillColor("#333")
    .text(`Mentor     : ${mentor.name}`)
    .text(`Department : ${mentor.department || "N/A"}`)
    .text(
      `Week       : ${new Date(report.weekStartDate).toDateString()} — ${new Date(
        report.weekEndDate
      ).toDateString()}`
    )
    .text(`Generated  : ${new Date().toDateString()}`)
    .moveDown(0.8);

  // ── Summary ──
  doc
    .fontSize(13)
    .fillColor("#14532d")
    .text("Summary", { underline: true })
    .moveDown(0.3)
    .fontSize(11)
    .fillColor("#333")
    .text(`Total Students       : ${report.totalStudents}`)
    .text(`Present              : ${report.presentCount}`)
    .text(`Absent               : ${report.absentCount}`)
    .text(`Low Attendance (<75%): ${report.lowAttendanceCount}`)
    .moveDown(0.8);

  // ── Low Attendance Students ──
  if (report.lowAttendanceStudents?.length) {
    doc
      .fontSize(13)
      .fillColor("#14532d")
      .text("Low Attendance Students", { underline: true })
      .moveDown(0.3);

    report.lowAttendanceStudents.forEach((s, i) => {
      doc
        .fontSize(11)
        .fillColor("#333")
        .text(`${i + 1}. ${s.student?.name || "N/A"} (${s.student?.rollNo || "N/A"})`)
        .text(`   Attendance : ${s.attendancePercent}%`)
        .text(`   Reason     : ${s.reason || "Not provided"}`)
        .moveDown(0.3);
    });

    doc.moveDown(0.5);
  }

  // ── Sessions Summary ──
  if (report.sessionsSummary?.length) {
    doc
      .fontSize(13)
      .fillColor("#14532d")
      .text("Sessions Summary", { underline: true })
      .moveDown(0.3);

    report.sessionsSummary.forEach((s, i) => {
      doc
        .fontSize(11)
        .fillColor("#333")
        .text(`${i + 1}. Student : ${s.student?.name || "N/A"}`)
        .text(`   Purpose  : ${s.purpose || "N/A"}`)
        .text(`   Outcome  : ${s.outcome || "N/A"}`)
        .moveDown(0.3);
    });
  }

  // ── Footer ──
  doc
    .moveDown(1)
    .moveTo(50, doc.y)
    .lineTo(560, doc.y)
    .strokeColor("#14532d")
    .stroke()
    .moveDown(0.5)
    .fontSize(10)
    .fillColor("#888")
    .text("This report was auto-generated by Mentoring Hub.", {
      align: "center",
    });

  doc.end();
};

module.exports = { generateWeeklyReportPDF };